apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cold-harbor-chart.name" . }}-configmap
  labels:
    {{- include "cold-harbor-chart.labels" . | nindent 4 }}
data:
  PORT: 3000
  PATH_TO_DB: /app/cold_harbor_data/cold_harbor.db