apiVersion: v1
kind: ConfigMap
metadata:
  name: cold-harbor-configmap
  labels:
    {{- include "cold-harbor-chart.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.port | quote }}
  PATH_TO_DB: {{ .Values.pathToDb | quote }}