apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cold-harbor-chart.fullname" . }}
  labels:
    {{- include "cold-harbor-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cold-harbor-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cold-harbor-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "cold-harbor-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "cold-harbor-chart.name" . }}-db
              mountPath: /app/data
      volumes:
        - name: cold-harbor-db
          hostPath:
            path: /data/cold-harbor-db
            type: DirectoryOrCreate
        - name: cold-harbor-config
          configMap:
            name: cold-harbor-configmap
